config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Judge::Engine => '/judge'
  resources :requests
  root 'requests#index'
  get '/queue',		to: 	'queue#queue'
  get '/whatis',	to: 	'static#whatis'
  get '/help',		to: 	'static#help'
  authenticated :user do
	  get '/player',	to: 	'player#player'
  end
  get '/player', to: redirect('/users/sign_in')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery prepend: true
	@stream = nil


=begin
	client = Twitch::Client.new client_id: "#{configatron.twitch.clientid}"
	inchan = client.get_streams({user_id: configatron.twitch.channel}).data
	if inchan.empty? == true
		@stream = "offline"
		print "offline \n" * 5
	elsif inchan.empty? == false
		@stream = "online"
		print "online \n" * 5
	end
=end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
	def player
		#@requests = Request.all
		@requests = Request.order(sort_column + ' ' + sort_direction)
		@url = params[:url]
	end

	def play
		print "hello" * 5
	end

	helper_method :sort_column, :sort_direction

	private
	
	def sort_column
		Request.column_names.include?(params[:sort]) ? params[:sort] : "id"
	end
	
	def sort_direction
		%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/controllers/queue_controller.rb
class QueueController < ApplicationController
	def queue
		#@requests = Request.all
		@requests = Request.order(sort_column + ' ' + sort_direction)
	end
	helper_method :sort_column, :sort_direction

	private
	
	def sort_column
		Request.column_names.include?(params[:sort]) ? params[:sort] : "id"
	end
	
	def sort_direction
		%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
	end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	before_action :set_request, only: [:show, :edit, :update, :destroy]
  	
	# GET /requests
	# GET /requests.json
	def index
		@requests = Request.new
	end

	# GET /requests/1
	# GET /requests/1.json
	def show
	end

	# GET /requests/new
	def new
		@request = Request.new
	end

	# GET /requests/1/edit
	def edit
		@request = Request.find(params[:id])
	end


	# POST /requests
	# POST /requests.json
	def create
		@request = Request.new(request_params)

		respond_to do |format|
			if @request.save
				format.html { redirect_to @request, notice: 'Request was successfully created.' }
			        format.json { render :show, status: :created, location: @request }
			else
				format.html { render :new }
				format.json { render json: @request.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /requests/1
	# PATCH/PUT /requests/1.json
	def update
		respond_to do |format|
			if @request.update(request_params)
				format.html { redirect_to @request, notice: 'Request was successfully updated.' }
				format.json { render :show, status: :ok, location: @request }
			else
				format.html { render :edit }
				format.json { render json: @request.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /requests/1
	# DELETE /requests/1.json
	def destroy
		@request.destroy
		respond_to do |format|
			format.html { redirect_to queue_url, notice: 'Request was successfully destroyed.' }
			format.json { head :no_content }
		end
	end
	
	
	private
	# Use callbacks to share common setup or constraints between actions.
	def set_request
		@request = Request.find(params[:id])
	end
	# Never trust parameters from the scary internet, only allow the white list through.
	def request_params
		params.require(:request).permit(:songurl, :twitchname)
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def whatis
	end

	def help
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "Radio TASBoat"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end



	def sortable(column, title = nil)
		title ||= column.titleize
		css_class = (column == sort_column) ? "current #sort_direction" : nil
		direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
		link_to title, :sort => column, :direction => direction
	end


end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/queue_helper.rb
module QueueHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
	<div class="row">
		<div class="col l6 s12">
			<h5 class="white-text">Radio TASBoat Request Page</h5>
			<p class="grey-text text-lighten-4">A site to request music for DwangoAC's stream.</p>
		</div>
		<div class="col l4 offset-l2 s12">
			<h5 class="white-text">Links</h5>
			<ul>
				<li><a class="grey-text text-lighten-3" href="http://twitch.tv/dwangoac">DwangoAC's Stream</a></li>
				<li><a class="grey-text text-lighten-3" href="http://fallenfocus.net:9988">IceCast Server Status</a></li>
				<li><a class="grey-text text-lighten-3" href="https://gitlab.com/MediaMagnet/radio-tasbot">GitLab Source</a></li>
			</ul>
		</div>
	</div>
</div>
<div class="footer-copyright">
	<div class="container">
 	<i class="material-icons left">copyright</i> 2018 MediaMagnet
		<a class="grey-text text-lighten-4 right" href="http://twitch.tv/mediamagnet">Other Stuff Soon.</a>
	</div>
</div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar-fixed">
	<nav>
		<div class="nav-wrapper">
			<a href="#!" class="brand-logo center"><i class="material-icons left">play_circle_outline</i> Radio Free TASBoat Requests</a>
			<!--<a href="#!" data-target="mobile-nav" class="sidenav-trigger"><#% mi.icon.menu %></a>-->
			<ul class="left hide-on-med-and-down">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Queue", queue_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<li><%= link_to "What is?", whatis_path %></li>
				<% if user_signed_in? == true %>
					<li><%= link_to "Admin", rails_admin_path %></li>
					<li><%= link_to "Player", player_path %></li>
				<% end %>
			</ul>
		</div>
	</nav>
</div>
<!--<ul class="sidenav" id="mobile-nav">
	<li><#%= link_to "Home", root_path %></li>
	<li><#%= link_to "Queue", queue_path %></li>
	<li><#%= link_to "Help", help_path %></li>
	<li><#%= link_to "What is?", whatis_path %></li>
	<#% if user_signed_in? == true %>
		<li><#%= link_to "Admin", rails_admin_path %></li>
	<#% end %>
</ul>-->

app/views/layouts/_offline.html.erb
<div class="container">
	<div class="row">
		<a href="#modal1" data-toggle="modal" class="waves-effect waves-red btn modal-trigger btn-changes center"><i class="material-icons left">warning</i>Channel Offline</a>
		<div id="modal1" class="modal">
			<div class="modal-content">
				<h4><i class="material-icons left large">warning</i>Channel Offline</h4><p>The twitch stream is currently offline, and we are not taking requests at current.</p>
			</div>
			<div class="modal-footer">
				<a href="#!" class="modal-action modal-close waves-effect waves-green btn"><i class="material-icons left small">exit_to_app</i>Okay</a>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<% channel = RestClient.get "https://api.twitch.tv/helix/streams?user_id=#{configatron.twitch.channel}", {:'Client-ID' => configatron.twitch.clientid} %>
<% inchan = Oj.load(channel).fetch('data').first %>
<% if inchan.nil? == true %>
	<% @stream = "offline" %>
<% elsif inchan.nil? == false %>
	<% @stream = "online" %>
<% end %>

<!DOCTYPE html>
<html>
  <head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= csrf_meta_tags %>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <header><%= render 'layouts/header.html.erb' %></header>
	  <% flash.each do |message_type, message| %>
		  <%= javascript_tag "Materialize.toast('#{message}', 4000)" %>
	  <% end %>
  
	  <main>
	  <% if @stream == "offline" %>
		  <%= render 'layouts/offline.html.erb' %>
	  <% end %>
	  <%= yield %>
	<div class="fixed-action-btn horizontal">
		<% if user_signed_in? == true %>
			<a class="btn-floating btn-large red darken-1">
				<i class="large material-icons">lock_outline</i>
			</a>
			<ul>
				<li><%= link_to "Sign out", destroy_user_session_path, { :method=>:delete, :class=>"btn waves-effect waves-red" } %></li> 
			</ul>

		<% else %>
			<a class="btn-floating btn-large green darken-2">
				<i class="large material-icons">lock_open</i>
			</a>
			<ul>
				<li><%= link_to "Sign in", new_user_session_path, { :class=>"btn waves-effect waves-red" } %></li> 
			</ul>
		<% end %>
		
	</div>
  	</main>
	<footer class="page-footer"><%= render 'layouts/footer.html.erb' %></footer>
  </body>
</html>

app/views/player/_play.html.erb
<% Yt.configuration.api_key = configatron.yt.api %>
<% video = Yt::Video.new id: @url %>
<div class="yt-vid">
	<!--<#%= YouTubeAddy.youtube_embed_url('https://youtu.be/'+@url).html_safe %>-->
	<!--<#%= video.embed_html.html_safe %>-->
	<iframe  width="512" height="288" src='https://www.youtube.com/embed/<%= @url %>?rel=0&autoplay=1' frameborder='0' allowfullscreen></iframe>
</div>

app/views/player/player.html.erb
<% provide(:title, "Player") %>
<% VideoInfo.provider_api_keys = { youtube: configatron.yt.api } %>
<div class="container text">
	<table class="striped highlight centered">
		<thead>
			<tr>
			<!--<th><#%= link_to "ID", :sort => "id" %></th>-->
				<th><%= sortable "id" %></th>
				<th>Requested Song</th>
				<th>Twitch name</th>
				<% if user_signed_in? == true %>
					<th><%= sortable "created_at", "Submitted" %></th>
					<!--<th><#%= link_to "Subbmited", :sort => "created_at" %></th>-->
				<% end %>
				<th colspan="3"></th>
			</tr>
		</thead>	
			<tbody>
				<% @requests.each do |request| %>
				<% video = VideoInfo.new("#{request.songurl}") %>
				<% vname = video.title %>
				<% vauthor = video.author %>
				<% vtitle = "#{vname} - \[#{vauthor}\]" %>
				<tr>
					<td><%= request.id %></td>
					<td><%= link_to vtitle, "#{request.songurl}", target: :_blank %></td>
					<td><%= request.twitchname %></td>
					<td><%= request.created_at %></td>
					<% if request.songurl.include? "https://youtu.be/" %>
						<td><%= link_to 'Play', 'player?url='+request.songurl[17..-1] %></td>
					<% elsif request.songurl.include? "http://youtu.be/" %>
						<td><%= link_to 'Play', 'player?url='+request.songurl[16..-1] %></td>
					<% elsif request.songurl.include? "https://www.youtube.com/watch?v=" %>
						<td><%= link_to 'Play', 'player?url='+request.songurl[32..-1] %></td>
					<% elsif request.songurl.include? "http://www.youtube.com/watch?v=" %>
						<td><%= link_to 'Play', 'player?url='+request.songurl[31..-1] %></td>
					<% end %>
					<td><%= link_to 'Edit', edit_request_path(@requests) %></td>
					<td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?'  } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<% if @url != nil %>
		<div class='row' id='player'>
			<%= render 'player/play' %>
		</div>
	<% end %>	
</div>

app/views/queue/queue.html.erb
<% provide(:title, "Queue") %>
<% VideoInfo.provider_api_keys = { youtube: configatron.yt.api } %>
<div class="container text">
	<table class="striped highlight centered">
		<thead>
			<tr>
			<!--<th><#%= link_to "ID", :sort => "id" %></th>-->
				<th><%= sortable "id" %></th>
				<th>Requested Song</th>
				<th>Twitch name</th>
				<% if user_signed_in? == true %>
					<th><%= sortable "created_at", "Submitted" %></th>
					<!--<th><#%= link_to "Subbmited", :sort => "created_at" %></th>-->
				<% end %>
				<th colspan="3"></th>
			</tr>
		</thead>	
			<tbody>
				<% @requests.each do |request| %>
				<% video = VideoInfo.new("#{request.songurl}") %>
				<% vname = video.title %>
				<% vauthor = video.author %>
				<% vtitle = "#{vname} - \[#{vauthor}\]" %>
				<tr>
					<td><%= request.id %></td>
					<td><%= link_to vtitle, "#{request.songurl}", target: :_blank %></td>
					<td><%= request.twitchname %></td>
					<% if user_signed_in? == true %>
						<td><%= request.created_at %></td>
						<td><%= link_to 'Show', request %></td>
						<td><%= link_to 'Edit', edit_request_path(@requests) %></td>
						<td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?'  } %></td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/requests/_form.html.erb
<% channel = RestClient.get "https://api.twitch.tv/helix/streams?user_id=#{configatron.twitch.channel}", {:'Client-ID' => configatron.twitch.clientid} %>
<% inchan = Oj.load(channel).fetch('data').first %>
<% print "#{inchan} \n" %>
<% if inchan.nil? == true %>
	<% @stream = "offline" %>
<% elsif inchan.nil? == false %>
	<% @stream = "online" %>
<% end %>

<%= simple_form_for(@requests) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="input-field col s6 form-inputs">
	  <%= f.input :songurl, placeholder:"Song link", label:false, input_html: {value: "https://"} %>
  </div>

  <div class="input-field col s6 form-inputs">
	  <%= f.input :twitchname, placeholder:"Twitch name", label:false, required:true, :validate => true %>
  </div>

  <div class="col s12 form-actions">
	  <% if @stream == "offline" %>
		  <%= f.button :submit, class: "btn disabled" %>
	  <% else %>
		  <%= f.button :submit, class: "btn waves-effect waves-green" %>
	  <% end %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<div class="text container">
	<div class="row">
	<h3>Edit your request:</h3>
	</div>
	<div class="row">
		<div class="col s12">
			<%= render 'form', request: @requests %>
		</div>
	</div>
	<div class="row">
		<div class="col s2">
			<%= link_to 'Show', @request %> |
		</div>
		<div class="col s2">
			<%= link_to 'Back', requests_path %>
		</div>
	</div>
</div>

app/views/requests/index.html.erb
<% provide(:title, "Requests") %>

<% if @stream == "offline" %>
	<%= render 'layouts/offline.html.erb' %>
<% end %>
<div class="container text">
	<div class="row">
		<div class="col s8">
			<p>Welcome to the request page for Radio Free TASBot please make a request below. 
			<br>
			Guidelines and rules:
			<hr>
			<ul class="browser-default" style="list-style-type:square">
				<li>No requests over ten minutes in duration.</li>
				<li>No more than two requests in the queue at a time.</li>
				<li>Not all requests will be played in tonights stream. Those that are not played will be played at the begining of the next stream.</li>
				<li>Keep the music clean! Weird is fine. Vulgar is not.</li>
				<li>The DJ and the Streamer reserve the right to veto any song.</li>
			</ul>
			</p>
		</div>
	</div>
	<div class="row">
		<div class="col s12">
			<%= render 'form', request: @requests %>
		</div>
	</div>

</div>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<% VideoInfo.provider_api_keys = { youtube: configatron.yt.api } %>
<% video = VideoInfo.new("#{@request.songurl}") %>
<% vtitle = video.title %>
<div class="container text">
	<div class="row">
		<div class"col s12">
			<p>Your request:</p>
		</div>
	</div>
	<div class="row">
		<div class="col s6">
			<strong>Song link:</strong>
			<br>
			<%= vtitle %><br>
			<%= @request.songurl %>
		</div>
		<div class="col s6">
			<strong>Your Twitch Username:</strong>
			<br>
			<%= @request.twitchname %>
		</div>
	</div>
	<div class="row">
		<%= link_to 'Edit', edit_request_path(@request), { :class => 'waves-effect waves-light text btn' } %>
		<%= link_to 'Back', queue_path, { :class => 'waves-effect waves-light text btn' } %>
	</div>
</div>